# Centralized Local User Management
# https://github.com/dehesselle/clum
#
# This is how you assign users (from ../../common/vars/main.yml)
# to your server.
#
- include: ../../common/tasks/create_user.yml
  with_items:
    - "{{ u220815 }}"
    - "{{ u224711 }}"
