- name: copy helper script
  copy:
    src: clean_passwd.sh
    dest: /tmp
    owner: root
    group: root
    mode: 0755
  become: true
- name: create cleansed temporary file with helper script
  command: /tmp/clean_passwd.sh {{ clean_file }} /tmp/passwd
- name: replace existing {{ clean_file }}
  command: mv /tmp/passwd {{ clean_file }}
  become: true
- name: set {{ clean_file }} permissions
  file:
    path: "{{ clean_file }}"
    owner: root
    group: root
    mode: 0644
  become: true
- name: remove helper script
  file:
    path: /tmp/clean_passwd.sh
    state: absent
  become: true

