# Centralized Local User Management
# https://github.com/dehesselle/clum
#
- name: create primary group for user {{ item.uname }}
  include: create_group.yml gname="{{ item.uname }}" gid="{{ item.uid }}"
- name: create secondary groups for user {{ item.uname }}
  include: create_group.yml gname="{{ item2.gname }}" gid="{{ item2.gid }}"
  with_items:
    - "{{ item.groups }}"
  loop_control:
    loop_var: item2
- name: create user {{ item.uname }}
  user:
    name: "{{ item.uname}}"
    comment: "{{ item.rname }}"
    uid: "{{ item.uid }}"
    group: "{{ item.uname }}"
    groups: "{{ item.groups|map(attribute='gname')|list }}"
    createhome: yes
    shell: /bin/bash
    # password = start123
    password: >
      $6$OLXFYXdUhkfqAVyU$DUG2pvNERMzMzAL
      XF0jVu6NQDk2x7rt2XX5Uv6vLkjgsjjemdy
      Xt6oH.uNX32dN1SVjFqNDQtdIpfpAxmoL9P.
    state: present
    update_password: on_create
  become: true
  # In case of a pre-existing home directory we need to make sure it's owned
  # by the user.
- name: set owner and group for /home/{{ item.uname }}
  include: set_homedir_og.yml uname="{{ item.uname }}"

