# Centralized Local User Management
# https://github.com/dehesselle/clum
#
- name: create group {{ gname }}
  group:
    name: "{{ gname }}"
    gid: "{{ gid }}"
    state: present
  become: true
  when: gid|int >= clum_first_group.gid|int

