# Centralized Local User Management
# https://github.com/dehesselle/clum
#
- import_tasks: install_libselinux.yml
- include_tasks: clean_group.yml clean_file=/etc/group
- include_tasks: clean_passwd.yml clean_file=/etc/passwd first_id={{ clum_first_user.uid }}
- include_tasks: clean_passwd.yml clean_file=/etc/group first_id={{ clum_first_group.gid }}
