# Centralized Local User Management
# https://github.com/dehesselle/clum
#
# home directory may have been created in a non-default location
- name: check if home directory is in expected path
  stat:
    path: /home/{{ uname }}
  register: home_dir
- name: get fully qualified and unlinked location
  command: readlink -f /home/{{ uname }}
  register: home_dir_target
  when: home_dir.stat.exists
- name: set owner and group for {{ home_dir_target.stdout }}
  file:
    path: "{{ home_dir_target.stdout }}"
    owner: "{{ uname }}"
    group: "{{ uname }}"
    recurse: yes
    state: directory
  when: home_dir_target.rc == 0
  become: true
