# Centralized Local User Management
# https://github.com/dehesselle/clum
#
# See the examples below on how to add your users and 
# groups to this file.
#
# groups
#mygroup1:
#  gid: 100001
#gname: mygroup1
#mygroup2:
#  gid: 100002
#  gname: mygroup2
#mygroup3:
#  gid: 100003
#  gname: mygroup3
##
# users
#u224711:
#  uid: 1224711
#  uname: u224711
#  rname: John Doe
#  groups:
#    - "{{ mygroup1 }}"
#u220815:
#  uid: 1220815
#  uname: u220815
#  rname: Jane Doe
#  groups:
#    - "{{ mygroup2 }}"
#    - "{{ mygroup3 }}"
